name: Release

on:
  push:
    branches:
    - 'release/*'
    tags:
    - 'release/*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: mcipollo/release-action@v1.11.1
      with:
        token: ${{ secrets.YOUR_GITHUB_TOKEN}}