
name: Release and deploy 

# trigger (on event)
on: 
  push:
    branches:
    - 'main'
    tags:
    - 'v[0-9]+.[0-9]+'



#try
#jobs in the workflow
jobs:
  release-and-deploy:
  #job name
  #OS that this job will be running on
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '#NORUN")"

    #list of steps to perform the task
    steps:
    - name: echo the branch name
      run: echo "curent branch - $ {{github.ref_name}}"
    - name: checkout the branch
      uses: actions/checkout@v3
      with:
        ref: ${{github.ref_name}}
    - name: create a release
      uses: ncipollo/release-action@v1.11.1
      with: 
        token: ${{ secrets.YOUR_GITHUB_TOKEN }}
    - name: deploy to railway
      uses: devtomio/action-railway@v1.1.4
      with:
        railway_token: ${{ secrets.RAILWAY_TOKEN }}
    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        # For posting a rich message using Block Kit
        payload: |
          {
            "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "DipSA55 CI/CD Assignment Submission",
                  "emoji": true
                }
              },
              {
                "type":"section",
                "fields":[
                  {
                      "type":"mrkdwn",
                      "text":"*Name:*\nSharmaine Cheng Jing Yi"
                  },
                  {
                      "type":"mrkdwn",
                      "text":"*Metriculation:*\nA0101376N"
                  }
                ]
              },
              {
                "type":"section",
                "fields":[
                  {
                      "type":"mrkdwn",
                      "text":"*Email:*\n<mailto:e1043489@u.nus.edu|e1043489@u.nus.edu>"
                  },
                  {
                      "type":"mrkdwn",
                      "text":"*Repository:*\n<${{ secrets.MY_GITHUB_URL }}|${{ secrets.MY_GITHUB_URL }}>"
                  }
                ]                
              },
              {
                "type":"section",
                "fields":[
                  {
                      "type":"mrkdwn",
                      "text":"*Deployment:*\n<${{ secrets.RAILWAY_URL }}|${{ secrets.RAILWAY_URL }}>"
                  } 
                ]
              },
              {
                "type":"section",
                "fields":[
                  {
                      "type":"mrkdwn",
                      "text":"<${{ secrets.RAILWAY_URL }}|Open Application>"
                  }
                ]
              }       
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK


