
name: Release and deploy todo

# trigger (on event)
on: [push]

#try
#jobs in the workflow
jobs:
  release-and-deploy:
  #job name
  #OS that this job will be running on
    runs-on: ubuntu-latest

    #list of steps to perform the task
    steps:
    - name: echo the branch name
      run: echo "curent branch - $ {{github.ref_name}}"
    - name: checkout the branch
      uses: actions/checkout@v3
      with:
        ref: ${{github.ref_name}}

    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        # For posting a rich message using Block Kit
        payload: |
          {
            "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "DipSA55 CI/CD Assignment Submission",
                  "emoji": true
                }
              },
              {
                "type":"section",
                "fields":[
                  {
                      "type":"mrkdwn",
                      "text":"Name:*\nName"
                  },
                  {
                      "type":"mrkdwn",
                      "text":"Metriculation:*\nMetriculation:"
                  }
                ]
              },
              {
                "type":"section",
                "fields":[
                  {
                      "type":"mrkdwn",
                      "text":"Email:*\nEmail"
                  },
                  {
                      "type":"mrkdwn",
                      "text":"Repository:*\nRepository:"
                  }
                ]                
              },
              {
                "type":"section",
                "fields":[
                  {
                      "type":"mrkdwn",
                      "text":"Deployment:*\nDeployment"
                  } 
                ]
              }           
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK


